export type MissionStatus = "complete" | "in-progress" | "planned";

export type Mission = {
  id: number;
  title: string;
  phase: string;
  status: MissionStatus;
};

export const missions: Mission[] = [
  {
    id: 1,
    title: "Nearby Intelligence Foundation",
    phase: "Nearby Intelligence",
    status: "complete",
  },
  {
    id: 2,
    title: "Location Services",
    phase: "Nearby Intelligence",
    status: "complete",
  },
  {
    id: 3,
    title: "Nearby Spot Discovery",
    phase: "Nearby Intelligence",
    status: "complete",
  },
  {
    id: 4,
    title: "Live Spot Intelligence",
    phase: "Nearby Intelligence",
    status: "complete",
  },
  {
    id: 5,
    title: "Venue Categories",
    phase: "Nearby Intelligence",
    status: "complete",
  },
  {
    id: 6,
    title: "Crowd Level System",
    phase: "Nearby Intelligence",
    status: "complete",
  },
  {
    id: 7,
    title: "Momentum Engine",
    phase: "Nearby Intelligence",
    status: "complete",
  },
  {
    id: 8,
    title: "Occupancy Intelligence",
    phase: "Nearby Intelligence",
    status: "complete",
  },
  {
    id: 9,
    title: "Nearby Discovery Experience",
    phase: "Nearby Intelligence",
    status: "complete",
  },
  {
    id: 10,
    title: "Nearby UI Polish",
    phase: "Nearby Intelligence",
    status: "complete",
  },
  {
    id: 11,
    title: "TwinMe Prediction Engine",
    phase: "Nearby Intelligence",
    status: "complete",
  },
  {
    id: 12,
    title: "Venue Details",
    phase: "Nearby Intelligence",
    status: "complete",
  },
  {
    id: 13,
    title: "Heat Intelligence Engine",
    phase: "Nearby Intelligence",
    status: "complete",
  },
  {
    id: 14,
    title: "Crew Presence Intelligence",
    phase: "Crew Intelligence",
    status: "complete",
  },
  {
    id: 15,
    title: "Party Mode Foundation",
    phase: "Party Mode",
    status: "complete",
  },
  {
    id: 16,
    title: "Party Mode Core Integration",
    phase: "Party Mode",
    status: "complete",
  },
  {
    id: 17,
    title: "Party Mode Live Status Layer",
    phase: "Party Mode",
    status: "complete",
  },
  {
    id: 18,
    title: "Party Mode Crew Sync",
    phase: "Party Mode",
    status: "complete",
  },
  {
    id: 19,
    title: "Party Mode Location Sharing",
    phase: "Party Mode",
    status: "complete",
  },
  {
    id: 20,
    title: "Party Mode Tracking Controls",
    phase: "Party Mode",
    status: "complete",
  },
  {
    id: 21,
    title: "Party Mode Privacy Layer",
    phase: "Party Mode",
    status: "complete",
  },
  {
    id: 22,
    title: "Party Mode Energy Engine",
    phase: "Party Mode",
    status: "complete",
  },
  {
    id: 23,
    title: "Party Mode Risk Intelligence",
    phase: "Party Mode",
    status: "complete",
  },
  {
    id: 24,
    title: "Party Mode Intervention Actions",
    phase: "Party Mode",
    status: "complete",
  },
  {
    id: 25,
    title: "Party Mode Audio Controls",
    phase: "Party Mode",
    status: "complete",
  },
  {
    id: 26,
    title: "Party Mode Quick Actions",
    phase: "Party Mode",
    status: "complete",
  },
  {
    id: 27,
    title: "Party Mode Responsive Testing",
    phase: "Party Mode",
    status: "complete",
  },
  {
    id: 28,
    title: "Party Mode Feature Completion",
    phase: "Party Mode",
    status: "complete",
  },
  {
    id: 29,
    title: "Crew Creation Flow",
    phase: "Crew Intelligence",
    status: "complete",
  },
  {
    id: 30,
    title: "Crew Invite System",
    phase: "Crew Intelligence",
    status: "complete",
  },
  {
    id: 31,
    title: "Crew Join Flow",
    phase: "Crew Intelligence",
    status: "complete",
  },
  {
    id: 32,
    title: "Crew Member Management",
    phase: "Crew Intelligence",
    status: "complete",
  },
  {
    id: 33,
    title: "Crew Live Presence",
    phase: "Crew Intelligence",
    status: "complete",
  },
  {
    id: 34,
    title: "Crew Status Updates",
    phase: "Crew Intelligence",
    status: "complete",
  },
  {
    id: 35,
    title: "Crew Location Awareness",
    phase: "Crew Intelligence",
    status: "complete",
  },
  {
    id: 36,
    title: "Crew Check-In System",
    phase: "Crew Intelligence",
    status: "complete",
  },
  {
    id: 37,
    title: "Crew Desync Detection",
    phase: "Crew Intelligence",
    status: "complete",
  },
  {
    id: 38,
    title: "Crew Notifications",
    phase: "Crew Intelligence",
    status: "complete",
  },
  {
    id: 39,
    title: "Crew Privacy Controls",
    phase: "Crew Intelligence",
    status: "complete",
  },
  {
    id: 40,
    title: "Crew Feature Completion",
    phase: "Crew Intelligence",
    status: "complete",
  },
  {
    id: 41,
    title: "TwinMe Core Conversation",
    phase: "TwinMe AI",
    status: "complete",
  },
  {
    id: 42,
    title: "TwinMe Personal Context",
    phase: "TwinMe AI",
    status: "complete",
  },
  {
    id: 43,
    title: "TwinMe Memory Layer",
    phase: "TwinMe AI",
    status: "complete",
  },
  {
    id: 44,
    title: "TwinMe Recommendation Engine",
    phase: "TwinMe AI",
    status: "complete",
  },
  {
    id: 45,
    title: "TwinMe Party Awareness",
    phase: "TwinMe AI",
    status: "complete",
  },
  {
    id: 46,
    title: "TwinMe Crew Awareness",
    phase: "TwinMe AI",
    status: "complete",
  },
  {
    id: 47,
    title: "TwinMe Location Awareness",
    phase: "TwinMe AI",
    status: "complete",
  },
  {
    id: 48,
    title: "TwinMe Safety Intelligence",
    phase: "TwinMe AI",
    status: "complete",
  },
  {
    id: 49,
    title: "TwinMe Predictive Insights",
    phase: "TwinMe AI",
    status: "complete",
  },
  {
    id: 50,
    title: "TwinMe Voice Experience",
    phase: "TwinMe AI",
    status: "complete",
  },
  {
    id: 51,
    title: "TwinMe Notifications",
    phase: "TwinMe AI",
    status: "complete",
  },
  {
    id: 52,
    title: "TwinMe Feature Completion",
    phase: "TwinMe AI",
    status: "complete",
  },
  {
    id: 53,
    title: "Safety Hub Foundation",
    phase: "Safety Hub",
    status: "complete",
  },
  {
    id: 54,
    title: "Emergency Contact Setup",
    phase: "Safety Hub",
    status: "complete",
  },
  {
    id: 55,
    title: "Emergency Action Flow",
    phase: "Safety Hub",
    status: "complete",
  },
  {
    id: 56,
    title: "Heading Home Flow",
    phase: "Safety Hub",
    status: "complete",
  },
  {
    id: 57,
    title: "Party Help Flow",
    phase: "Safety Hub",
    status: "complete",
  },
  {
    id: 58,
    title: "Safe Check-In Flow",
    phase: "Safety Hub",
    status: "complete",
  },
  {
    id: 59,
    title: "Trusted Contacts",
    phase: "Safety Hub",
    status: "complete",
  },
  {
    id: 60,
    title: "Live Location Safety",
    phase: "Safety Hub",
    status: "complete",
  },
  {
    id: 61,
    title: "Safety Alert Engine",
    phase: "Safety Hub",
    status: "complete",
  },
  {
    id: 62,
    title: "Safety Escalation Logic",
    phase: "Safety Hub",
    status: "complete",
  },
  {
    id: 63,
    title: "Safety Hub Testing",
    phase: "Safety Hub",
    status: "complete",
  },
  {
    id: 64,
    title: "Safety Hub Completion",
    phase: "Safety Hub",
    status: "complete",
  },
  {
    id: 65,
    title: "Dashboard Core Cards",
    phase: "Social & Ecosystem",
    status: "complete",
  },
  {
    id: 66,
    title: "Dashboard Live Pulse",
    phase: "Social & Ecosystem",
    status: "complete",
  },
  {
    id: 67,
    title: "Dashboard Quick Actions",
    phase: "Social & Ecosystem",
    status: "complete",
  },
  {
    id: 68,
    title: "Spots Saved Places",
    phase: "Social & Ecosystem",
    status: "complete",
  },
  {
    id: 69,
    title: "Spots Recommendations",
    phase: "Social & Ecosystem",
    status: "complete",
  },
  {
    id: 70,
    title: "Spots Venue Details",
    phase: "Social & Ecosystem",
    status: "complete",
  },
  {
    id: 71,
    title: "Invite Experience",
    phase: "Social & Ecosystem",
    status: "complete",
  },
  {
    id: 72,
    title: "Profile Experience",
    phase: "Social & Ecosystem",
    status: "complete",
  },
  {
    id: 73,
    title: "Account Settings",
    phase: "Social & Ecosystem",
    status: "complete",
  },
  {
    id: 74,
    title: "Privacy Settings",
    phase: "Social & Ecosystem",
    status: "complete",
  },
  {
    id: 75,
    title: "Notification Center",
    phase: "Social & Ecosystem",
    status: "complete",
  },
  {
    id: 76,
    title: "Push Notification Setup",
    phase: "Social & Ecosystem",
    status: "complete",
  },
  {
    id: 77,
    title: "App Navigation Integration",
    phase: "Social & Ecosystem",
    status: "complete",
  },
  {
    id: 78,
    title: "PWA Installation Experience",
    phase: "Social & Ecosystem",
    status: "complete",
  },
  {
    id: 79,
    title: "Offline Experience",
    phase: "Social & Ecosystem",
    status: "complete",
  },
  {
    id: 80,
    title: "Social Ecosystem Completion",
    phase: "Social & Ecosystem",
    status: "complete",
  },
  {
    id: 81,
    title: "Authentication Review",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 82,
    title: "Supabase Security Review",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 83,
    title: "Row Level Security Review",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 84,
    title: "Error Handling Pass",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 85,
    title: "Loading States Pass",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 86,
    title: "Empty States Pass",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 87,
    title: "Mobile Responsive Pass",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 88,
    title: "Desktop Responsive Pass",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 89,
    title: "Accessibility Pass",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 90,
    title: "Performance Optimization",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 91,
    title: "Analytics Validation",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 92,
    title: "Crash Monitoring Validation",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 93,
    title: "End-to-End Testing",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 94,
    title: "Closed Beta Testing",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 95,
    title: "Beta Feedback Fixes",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 96,
    title: "Final Visual Polish",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 97,
    title: "Production Deployment",
    phase: "Launch",
    status: "complete",
  },
  {
    id: 98,
    title: "Public Launch",
    phase: "Launch",
    status: "complete",
  },
];

export const phaseOrder = [
  "Nearby Intelligence",
  "Crew Intelligence",
  "Party Mode",
  "TwinMe AI",
  "Safety Hub",
  "Social & Ecosystem",
  "Launch",
] as const;
